### ISSUE TITLE
Soil temperature at depth varying with reqhgt

### ISSUE THREAD

**Issue by hgfell** [ilyamaclean/microclimc#13]
When running runwithNMR I have found the soil temperature at depths varies with the reqhgt. For example when calucating the soil temperature at a 10cm depth across a year (2010) using era5 climate data, NCEP precip data and the evergreen_broadleaf_forest vegitation perameters and varying reqhgt from 0.1-2 (seq(0.1, 2, 0.1)), I observe a variation in soil temp at 10cm depth with lower soil temperatures found at in models run with higher reqhgt. 
[10cm_annual_soil_vary](https://user-images.githubusercontent.com/45235885/215525355-9f0485f5-91b1-4600-96cb-4ac985bd31d4.png). 

Is this correct? I may have misunderstood what reqhgt represents but i don't understand how varying the required prediction height should impact the soil depth temperature as they should both lie on the combined below canopy and below ground temperature profile and altering the reqhgt should move the height the temperature is reported on the profile but not the profile its self? 

Attatched is the script (https://github.com/Plague-Madagascar/micro_mad/blob/main/04_checking_potential_error_in_soil_temp.R) and data (https://github.com/Plague-Madagascar/micro_mad/blob/main/point_clim.rds) used to produce the plot.

Many Thanks

Henry

**Comment by ilyamaclean** [comment]
Sorry - hadn't anticipated users would use runwithNMR for soil temperature, as there is no need to run an above ground microclimate model for that - you should use runNMR instead, which omits the step of running the above ground microclimate model. But I realise this (a) this isn't clear in documentation and (b) users might want both above and below on one model run, so have put in a fix that deals with that.
